### ISSUE TITLE
Suggest to include Favourites

### ISSUE THREAD

**Issue by hannah23280** [plaskowski/EmbeddedBrowserIntellijPlugin#54]
Hi,
  Is it possible to provide the feature to add our favourites? So that we do not have to manually type the URL address

**Comment by plaskowski** [comment]
Hi @hannah23280,
thank you for you submission.
Please elaborate a little more on the actual need:
How often you expect to add/remove a site from favourites?
How many favourite sites you expect to have?
Would you be ok with configuring the favourites in a configuration file instead of a UI?

Implementing fully fledged favourites sites list management sounds like a lot of UI work but maybe we can come up with something simpler that will satisfy your needs.
Cheers.

**Comment by plaskowski** [comment]
Here is an example solution. Let me know your thoughts on this.

#### Hand-crafted home page
You could write a simple HTML page (single HTML file stored locally) that contains clickable links and use it as the home page by using a local file URL like this: 
`file:///Users/plaskowski/dev/private/test/bookmarks.html`
This way the only thing missing on plugin side would be a "home" button which is trivial to add.
Of course you could use any online site (e.g. dedicated online service for bookmarks) in the same manner.

**Comment by plaskowski** [comment]
Hi @hannah23280,
I have added the home page button in 1.5.0 version.
To configure the home page url check out initial_url in Configuration section in project readme.
Cheers.
